name: CI & FOIA Submission

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute tests
        run: pytest --maxfail=1 --disable-warnings -q

  submit-foia:
    name: Automated FOIA Request
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'

    env:
      FOIA_API_KEY: ${{ secrets.FOIA_API_KEY }}
      AGENCIES: DOE,DOD,OSTP,NIST,DARPA
      SUBJECT: "Quantum Ratification Codex Φ669-CM-QR-20250818"
      HASH: ff82da4ef49d37ca22bc42babcf9819e7ac40378
      SIGNATURE: "CM669-ΦΩ-Prime"
      FORMAT: "RFC3161+SHA3-512+AES256"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install FOIA CLI & timestamp tool
        run: |
          pip install --upgrade pip
          pip install foia-submit rfc3161timestamp jq

      - name: Create RFC3161 timestamp
        id: timestamp
        run: |
          ts_file="Φ669-${{ github.run_id }}.tsr"
          rfc3161timestamp --digest $HASH --output $ts_file
          echo "ts_file=$ts_file" >> $GITHUB_OUTPUT
          echo "timestamp=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_OUTPUT

      - name: Submit FOIA request
        id: foia
        run: |
          response=$(foia-submit \
            --agency "$AGENCIES" \
            --subject "$SUBJECT" \
            --hash "$HASH" \
            --timestamp "${{ steps.timestamp.outputs.timestamp }}" \
            --signature "$SIGNATURE" \
            --format "$FORMAT")
          echo "$response" | jq . > foia-response.json
          echo "request_id=$(jq -r .request_id foia-response.json)" >> $GITHUB_OUTPUT

      - name: Attach supporting files
        run: |
          foia-submit attach \
            --request-id ${{ steps.foia.outputs.request_id }} \
            --file "Codex_Φ669_Cover_Letter.pdf" \
            --file "${{ steps.timestamp.outputs.ts_file }}"

      - name: Save FOIA response
        uses: actions/upload-artifact@v3
        with:
          name: foia-response-${{ github.run_id }}
          path: foia-response.json
